name: Deploy

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [backend-ci, frontend-ci]
    
    steps:
    - uses: actions/checkout@v3
    
    # Backend Deployment (Heroku)
    - name: Deploy Backend to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      if: github.ref == 'refs/tags/v*.*.*'
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "your-bookreader-api"
        heroku_email: "your-email@example.com"
        usedocker: true
        appdir: "./backend"
        
    # Frontend Deployment (Vercel)
    - name: Install Vercel CLI
      run: npm install -g vercel
      
    - name: Deploy Frontend to Vercel
      working-directory: ./frontend
      run: |
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        